const express = require('express');
const cors = require('cors');
const path = require('path');
const fs = require('fs');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const multer = require('multer');

const db = require('./db');
const { analyzeFraudRisk } = require('./fraudEngine');

const app = express();
const PORT = process.env.PORT || 3000;
const JWT_SECRET = process.env.JWT_SECRET || 'digital-land-registry-secret-key-2026';

// Uploads setup
const UPLOADS_DIR = path.join(__dirname, 'uploads');
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

// Create sample mock files if not present
const sampleFiles = ['sample_deed.pdf', 'sample_survey.pdf', 'sample_id.pdf', 'suspect.pdf'];
sampleFiles.forEach(fileName => {
  const filePath = path.join(UPLOADS_DIR, fileName);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(
      filePath,
      `%PDF-1.4 Mock Official Land Registry Document: ${fileName}\nGenerated by Digital Land Record & Property Registration Platform.\nTimestamp: ${new Date().toISOString()}`
    );
  }
});

// Configure Multer storage
const storage = multer.diskStorage({
  destination: (req, file, cb) => cb(null, UPLOADS_DIR),
  filename: (req, file, cb) => {
    const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1e9);
    const ext = path.extname(file.originalname);
    cb(null, file.fieldname + '-' + uniqueSuffix + ext);
  }
});
const upload = multer({ storage });

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Serve static UI and uploads
app.use(express.static(path.join(__dirname, 'public')));
app.use('/uploads', express.static(UPLOADS_DIR));

// JWT Verification Middleware
function authenticateToken(req, res, next) {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];

  if (!token) {
    return res.status(401).json({ error: 'Access token required' });
  }

  jwt.verify(token, JWT_SECRET, (err, user) => {
    if (err) return res.status(403).json({ error: 'Invalid or expired session token' });
    req.user = user;
    next();
  });
}

// Admin Check Middleware
function requireAdmin(req, res, next) {
  if (!req.user || req.user.role !== 'admin') {
    return res.status(403).json({ error: 'Administrator privileges required for this action' });
  }
  next();
}

// ==========================================
// AUTHENTICATION ENDPOINTS
// ==========================================

// User Registration
app.post('/api/auth/register', (req, res) => {
  try {
    const { name, email, password, role, idNumber, phone, address } = req.body;

    if (!name || !email || !password) {
      return res.status(400).json({ error: 'Name, email, and password are required' });
    }

    const existing = db.getUserByEmail(email);
    if (existing) {
      return res.status(400).json({ error: 'User with this email already exists' });
    }

    const hashedPassword = bcrypt.hashSync(password, 10);
    const userRole = role === 'admin' ? 'admin' : 'user';

    const newUser = {
      id: 'usr_' + Date.now(),
      name,
      email: email.toLowerCase(),
      password: hashedPassword,
      role: userRole,
      idNumber: idNumber || `AD-${Math.floor(1000 + Math.random() * 9000)}-${Math.floor(1000 + Math.random() * 9000)}`,
      phone: phone || '+1 (555) 000-0000',
      address: address || 'Registered Citizen Address',
      createdAt: new Date().toISOString()
    };

    db.createUser(newUser);
    db.addAuditLog('USER_REGISTERED', newUser.email, `New user registered as ${userRole.toUpperCase()}`);

    const token = jwt.sign({ id: newUser.id, email: newUser.email, role: newUser.role, name: newUser.name }, JWT_SECRET, { expiresIn: '24h' });

    res.status(201).json({
      message: 'User registered successfully',
      token,
      user: {
        id: newUser.id,
        name: newUser.name,
        email: newUser.email,
        role: newUser.role,
        idNumber: newUser.idNumber,
        phone: newUser.phone,
        address: newUser.address
      }
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error registering user: ' + err.message });
  }
});

// User Login
app.post('/api/auth/login', (req, res) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      return res.status(400).json({ error: 'Email and password are required' });
    }

    const user = db.getUserByEmail(email);
    if (!user) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    const isMatch = bcrypt.compareSync(password, user.password);
    if (!isMatch) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    const token = jwt.sign({ id: user.id, email: user.email, role: user.role, name: user.name }, JWT_SECRET, { expiresIn: '24h' });

    db.addAuditLog('USER_LOGIN', user.email, `User logged in successfully`);

    res.json({
      message: 'Login successful',
      token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role,
        idNumber: user.idNumber,
        phone: user.phone,
        address: user.address
      }
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error during login: ' + err.message });
  }
});

// Current User Profile
app.get('/api/auth/me', authenticateToken, (req, res) => {
  const user = db.getUserById(req.user.id);
  if (!user) return res.status(444).json({ error: 'User not found' });

  res.json({
    user: {
      id: user.id,
      name: user.name,
      email: user.email,
      role: user.role,
      idNumber: user.idNumber,
      phone: user.phone,
      address: user.address
    }
  });
});

// ==========================================
// LAND RECORDS & PUBLIC LEDGER ENDPOINTS
// ==========================================

// Get All Registered Lands (or User Owned Lands)
app.get('/api/lands', (req, res) => {
  const ownerId = req.query.ownerId;
  let lands = db.getAllLands();

  if (ownerId) {
    lands = lands.filter(l => l.ownerId === ownerId || l.ownerEmail === ownerId);
  }

  res.json(lands);
});

// Get Single Land Record Details
app.get('/api/lands/:id', (req, res) => {
  const land = db.getLandById(req.params.id);
  if (!land) {
    return res.status(404).json({ error: 'Land record not found in central ledger' });
  }
  res.json(land);
});

// Public Search Ledger
app.get('/api/ledger/search', (req, res) => {
  const query = (req.query.q || '').toLowerCase().trim();
  const lands = db.getAllLands();

  if (!query) return res.json(lands);

  const filtered = lands.filter(
    l =>
      l.id.toLowerCase().includes(query) ||
      l.pin.toLowerCase().includes(query) ||
      l.title.toLowerCase().includes(query) ||
      l.ownerName.toLowerCase().includes(query) ||
      l.district.toLowerCase().includes(query) ||
      l.deedRef.toLowerCase().includes(query)
  );

  res.json(filtered);
});

// ==========================================
// PROPERTY REGISTRATION PIPELINE (CITIZEN)
// ==========================================

// Submit New Property Registration Application
app.post(
  '/api/registrations',
  authenticateToken,
  upload.fields([
    { name: 'idProofDoc', maxCount: 1 },
    { name: 'saleDeedDoc', maxCount: 1 },
    { name: 'surveyMapDoc', maxCount: 1 }
  ]),
  (req, res) => {
    try {
      const user = db.getUserById(req.user.id);
      const {
        propertyTitle,
        district,
        sector,
        areaSqFt,
        zone,
        proposedValuationUsd,
        sellerName,
        sellerIdNumber,
        previousDeedRef,
        coordinatesJson
      } = req.body;

      if (!propertyTitle || !district || !areaSqFt || !proposedValuationUsd) {
        return res.status(400).json({ error: 'Property title, district, area, and proposed valuation are required' });
      }

      // Parse coordinates if provided
      let parsedCoords = [];
      if (coordinatesJson) {
        try {
          parsedCoords = typeof coordinatesJson === 'string' ? JSON.parse(coordinatesJson) : coordinatesJson;
        } catch (e) {
          console.warn('Failed to parse coordinates json', e);
        }
      }

      // Process uploaded files
      const documents = [];
      if (req.files) {
        if (req.files.idProofDoc && req.files.idProofDoc[0]) {
          const f = req.files.idProofDoc[0];
          documents.push({
            id: 'doc_' + Date.now() + '_1',
            name: f.originalname,
            type: 'ID Proof',
            filename: f.filename,
            url: '/uploads/' + f.filename
          });
        }
        if (req.files.saleDeedDoc && req.files.saleDeedDoc[0]) {
          const f = req.files.saleDeedDoc[0];
          documents.push({
            id: 'doc_' + Date.now() + '_2',
            name: f.originalname,
            type: 'Sale Deed',
            filename: f.filename,
            url: '/uploads/' + f.filename
          });
        }
        if (req.files.surveyMapDoc && req.files.surveyMapDoc[0]) {
          const f = req.files.surveyMapDoc[0];
          documents.push({
            id: 'doc_' + Date.now() + '_3',
            name: f.originalname,
            type: 'Survey Map',
            filename: f.filename,
            url: '/uploads/' + f.filename
          });
        }
      }

      // Fallback sample docs if user uploaded none in demo UI
      if (documents.length === 0) {
        documents.push(
          { id: 'doc_demo_1', name: 'Citizen_ID_Certificate.pdf', type: 'ID Proof', url: '/uploads/sample_id.pdf' },
          { id: 'doc_demo_2', name: 'Property_Sale_Agreement.pdf', type: 'Sale Deed', url: '/uploads/sample_deed.pdf' },
          { id: 'doc_demo_3', name: 'Cadastral_Survey_Plan.pdf', type: 'Survey Map', url: '/uploads/sample_survey.pdf' }
        );
      }

      const appData = {
        id: 'APP-' + new Date().getFullYear() + '-' + Math.floor(1000 + Math.random() * 9000),
        applicantId: user.id,
        applicantName: user.name,
        applicantEmail: user.email,
        applicantIdNumber: user.idNumber,
        applicantPhone: user.phone,
        propertyTitle,
        district,
        sector: sector || 'General Sector',
        areaSqFt: Number(areaSqFt),
        zone: zone || 'Residential',
        proposedValuationUsd: Number(proposedValuationUsd),
        sellerName: sellerName || 'Previous Registered Owner',
        sellerIdNumber: sellerIdNumber || 'AD-7766-5544-3322',
        previousDeedRef: previousDeedRef || 'SALE-DEED-' + Math.floor(1000 + Math.random() * 9000),
        coordinates: parsedCoords,
        documents,
        status: 'PENDING',
        fraudRisk: null,
        submittedAt: new Date().toISOString(),
        inspectorNotes: null,
        reviewedAt: null,
        reviewedBy: null
      };

      // Automatically run Fraud Detection Engine on submission
      const existingLands = db.getAllLands();
      const fraudAudit = analyzeFraudRisk(appData, existingLands);
      appData.fraudRisk = fraudAudit;

      if (fraudAudit.level === 'CRITICAL' || fraudAudit.level === 'HIGH') {
        appData.status = 'FLAGGED_FRAUD';
      }

      db.createApplication(appData);
      db.addAuditLog(
        appData.status === 'FLAGGED_FRAUD' ? 'FRAUD_FLAGGED' : 'APPLICATION_SUBMITTED',
        user.email,
        `Submitted application ${appData.id} for property "${propertyTitle}". Status: ${appData.status} (Fraud Score: ${fraudAudit.score}/100)`
      );

      res.status(201).json({
        message: 'Property registration application submitted successfully',
        application: appData
      });
    } catch (err) {
      res.status(500).json({ error: 'Server error processing registration: ' + err.message });
    }
  }
);

// Get My Applications (Citizen)
app.get('/api/registrations/my', authenticateToken, (req, res) => {
  const myApps = db.getApplicationsByUser(req.user.id);
  res.json(myApps);
});

// ==========================================
// ADMIN & FRAUD VERIFICATION PORTAL ENDPOINTS
// ==========================================

// Get All Registration Applications (Admin)
app.get('/api/admin/applications', authenticateToken, requireAdmin, (req, res) => {
  const apps = db.getAllApplications();
  const existingLands = db.getAllLands();

  // Refresh fraud score calculation on the fly for complete accuracy
  const enrichedApps = apps.map(app => {
    if (!app.fraudRisk || app.status === 'PENDING') {
      app.fraudRisk = analyzeFraudRisk(app, existingLands);
    }
    return app;
  });

  res.json(enrichedApps);
});

// Trigger Fraud Risk Re-audit
app.post('/api/admin/applications/:id/fraud-check', authenticateToken, requireAdmin, (req, res) => {
  const appItem = db.getApplicationById(req.params.id);
  if (!appItem) return res.status(404).json({ error: 'Application not found' });

  const existingLands = db.getAllLands();
  const auditResult = analyzeFraudRisk(appItem, existingLands);

  let newStatus = appItem.status;
  if (auditResult.level === 'CRITICAL' || auditResult.level === 'HIGH') {
    newStatus = 'FLAGGED_FRAUD';
  } else if (appItem.status === 'FLAGGED_FRAUD') {
    newStatus = 'PENDING';
  }

  const updated = db.updateApplicationStatus(appItem.id, newStatus, appItem.inspectorNotes, req.user.email, auditResult);

  db.addAuditLog('FRAUD_AUDIT_EXECUTED', req.user.email, `Executed manual fraud audit on application ${appItem.id}. Score: ${auditResult.score}/100 (${auditResult.level})`);

  res.json({
    message: 'Fraud risk audit executed',
    fraudRisk: auditResult,
    application: updated
  });
});

// Admin Approve Registration -> Creates Registered Land Record & Certificate
app.post('/api/admin/applications/:id/approve', authenticateToken, requireAdmin, (req, res) => {
  try {
    const { inspectorNotes } = req.body;
    const appItem = db.getApplicationById(req.params.id);

    if (!appItem) return res.status(404).json({ error: 'Application not found' });
    if (appItem.status === 'APPROVED') {
      return res.status(400).json({ error: 'Application has already been approved and registered' });
    }

    // Update status
    db.updateApplicationStatus(appItem.id, 'APPROVED', inspectorNotes || 'Approved after cadastral inspection and document verification.', req.user.name);

    // Create New Official Registered Land Record
    const newLandRecord = {
      id: 'LAND-' + new Date().getFullYear() + '-' + Math.floor(100 + Math.random() * 900),
      pin: 'PIN-' + Math.floor(100000 + Math.random() * 900000) + '-C' + Math.floor(1 + Math.random() * 9),
      title: appItem.propertyTitle,
      ownerId: appItem.applicantId,
      ownerName: appItem.applicantName,
      ownerEmail: appItem.applicantEmail,
      ownerIdNumber: appItem.applicantIdNumber,
      district: appItem.district,
      sector: appItem.sector,
      areaSqFt: appItem.areaSqFt,
      zone: appItem.zone,
      valuationUsd: appItem.proposedValuationUsd,
      taxStatus: 'PAID',
      taxValidTill: new Date().getFullYear() + 2 + '-12-31',
      status: 'ACTIVE',
      deedRef: 'DEED-REG-' + Math.floor(100000 + Math.random() * 900000),
      registrationDate: new Date().toISOString().split('T')[0],
      coordinates: appItem.coordinates && appItem.coordinates.length > 0 ? appItem.coordinates : [
        { x: 350 + Math.floor(Math.random() * 50), y: 350 + Math.floor(Math.random() * 50) },
        { x: 450 + Math.floor(Math.random() * 50), y: 350 + Math.floor(Math.random() * 50) },
        { x: 450 + Math.floor(Math.random() * 50), y: 450 + Math.floor(Math.random() * 50) },
        { x: 350 + Math.floor(Math.random() * 50), y: 450 + Math.floor(Math.random() * 50) }
      ],
      documents: appItem.documents,
      history: [
        {
          date: new Date().toISOString().split('T')[0],
          event: `Property Registered under title ${appItem.propertyTitle}`,
          actor: req.user.name + ' (Central Registry Inspector)'
        }
      ]
    };

    db.addLandRecord(newLandRecord);
    db.addAuditLog('REGISTRATION_APPROVED', req.user.email, `Approved property registration ${appItem.id}. Issued new land record ${newLandRecord.id} (Deed: ${newLandRecord.deedRef})`);

    res.json({
      message: 'Registration approved and official land deed issued',
      landRecord: newLandRecord
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error approving registration: ' + err.message });
  }
});

// Admin Reject Registration
app.post('/api/admin/applications/:id/reject', authenticateToken, requireAdmin, (req, res) => {
  try {
    const { inspectorNotes } = req.body;
    const appItem = db.getApplicationById(req.params.id);

    if (!appItem) return res.status(404).json({ error: 'Application not found' });

    const updated = db.updateApplicationStatus(
      appItem.id,
      'REJECTED',
      inspectorNotes || 'Registration rejected due to fraud flags or document discrepancies.',
      req.user.name
    );

    db.addAuditLog('REGISTRATION_REJECTED', req.user.email, `Rejected property registration ${appItem.id}. Reason: ${inspectorNotes}`);

    res.json({
      message: 'Registration application rejected',
      application: updated
    });
  } catch (err) {
    res.status(500).json({ error: 'Server error rejecting application: ' + err.message });
  }
});

// Admin Audit Logs
app.get('/api/admin/audit-logs', authenticateToken, requireAdmin, (req, res) => {
  const logs = db.getAuditLogs();
  res.json(logs);
});

// Start Express Server
app.listen(PORT, () => {
  console.log(`=======================================================`);
  console.log(`  DIGITAL LAND RECORD & PROPERTY REGISTRATION PLATFORM `);
  console.log(`  Running live at: http://localhost:${PORT}             `);
  console.log(`=======================================================`);
});
